= Contributing to picturesafe-search

Thank you for your interest in picturesafe-search!

We are pleased that you would like to contribute to our project!

== Getting started

Please read our https://github.com/picturesafe/picturesafe-search/[Getting started] guide and have a look at some https://github.com/picturesafe/picturesafe-search-samples/[code samples].

== Reporting a bug

If you have found a bug in picturesafe-search, please open an issue on our https://github.com/picturesafe/picturesafe-search/issues[issues list] and provide a description how to reproduce it.

== Feature request

If you need a feature that does not yet exist in the project, please open an issue on our https://github.com/picturesafe/picturesafe-search/issues[issues list] and provide a description of what you expect from the feature and how it should work.

== Contributing code

=== Fork and clone the repository

You will need to fork the picturesafe-search code and clone it to your local machine.
See https://help.github.com/en/github/getting-started-with-github/fork-a-repo[github help page] for help.

* Test your changes
* Run all tests via `mvn verify` and make sure that nothing is broken.
* Rebase your changes: Update your local repository with the most recent code of picturesafe-search and rebase your branch on top of the latest master branch. Please squash your changes into a single commit.
* Submit a pull request
* Push your local changes to your forked copy of the repository and submit a pull request.

=== Code style

The code formatting follows the Oracle Java Style Guide.

Please check your code against the checkstyle.xml of the project.

=== License Header

Please add the following license header line at the beginning of new Java classes.

[source,java]
----
/*
 * Copyright 2020 picturesafe media/data/bank GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
----

== Code of Conduct

Please read the https://github.com/picturesafe/picturesafe-search/blob/master/CODE_OF_CONDUCT.md[Code of Conduct].